# Generated by Django 2.0.2 on 2019-05-19 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tbpauth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='last name'),
        ),
    ]
